spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

server:
  port: ${PORT:8080}